#matrix:
#  include:
  # ENABLE AFTER ACE 6.4.3 is available.
    #- os: linux
    #  dist: trusty
    #  sudo: required
    #  compiler: clang
 #   - os: linux
 #     sudo: required
 #     dist: trusty
 #     group: deprecated-2017Q4
 #     compiler: gcc
 #     sudo: required
before_script:
  - apt-get update -qq
  - apt-get install clang
  - apt-get install libace-dev
  - apt-get install libncurses5-dev
  - apt-get install build-essential autoconf libtool make cmake git-core patch wget links zip unzip unrar g++
  - apt-get install openssl libssl-dev libmysqlclient15-dev libmysql++-dev libreadline6-dev zlib1g-dev libbz2-dev

build:
    script:
      - mkdir build
      - cd build
      - cmake ../ -G "CodeBlocks - Unix Makefiles"
      - cmake --build --target all -- -j8