language: cpp
os: linux
dist: xenial

matrix:
  include:
    - addons:
        apt:
          sources:
            - sourceline: 'ppa:mhier/libboost-latest'
            - ubuntu-toolchain-r-test
          packages:
            - boost1.67
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
    - addons:
        apt:
          sources:
            - sourceline: 'ppa:mhier/libboost-latest'
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - boost1.67
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"

branches:
  only:
    - master

before_install:
  - sudo apt-get install libmysqlclient-dev libmysql++-dev
  - eval "${MATRIX_EVAL}"

script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j8