language: cpp
os: linux
dist: xenial

matrix:
  include:
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"

branches:
  only:
    - master

before_install:
  - sudo apt-get install xutils-dev
  - sudo pip install conan
  - eval "${MATRIX_EVAL}"

script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release
  - make -j8