matrix:
  include:
    - os: linux
      sudo: required
      compiler: gcc

language: cpp

branches:
  only:
    - master

before_install:
  - sudo add-apt-repository ppa:george-edison55/cmake-3.x -y
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo add-apt-repository 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.9 main'
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install clang-3.9
  - sudo apt-get install libace-dev
  - sudo apt-get install lua5.2 liblua5.2 liblua5.2-dev
  - sudo apt-get install build-essential autoconf libtool make cmake git-core patch wget
  - sudo apt-get install libmysqlclient15-dev libmysql++-dev
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-6; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi

script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j8