language: cpp
os: linux
dist: xenial

matrix:
  include:
    - addons:
        apt:
          sources:
            - sourceline: 'ppa:mhier/libboost-latest'
          packages:
            - boost
      env:
        - MATRIX_EVAL="CC=gcc && CXX=g++"
    - addons:
        apt:
          sources:
            - sourceline: 'ppa:mhier/libboost-latest'
          packages:
            - boost
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"

branches:
  only:
    - master

before_install:
  - sudo apt-get install libmysqlclient-dev libmysql++-dev
  - eval "${MATRIX_EVAL}"

script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j8