language: cpp
os: linux
dist: trusty

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - sourceline: 'ppa:mhier/libboost-latest'
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - g++-7
            - boost1.67
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: linux
      addons:
        apt:
          sources:
            - sourceline: 'ppa:mhier/libboost-latest'
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
            - george-edison55-precise-backports
          packages:
            - g++-7 # Doesn't work otherwise, no idea why
            - clang-5.0
            - boost1.67
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

branches:
  only:
    - master

install:
  ############################################################################
  # Install a recent CMake
  ############################################################################
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v3.10/cmake-3.10.0-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    else
      brew install cmake || brew upgrade cmake
    fi
  - cmake --version

before_install:
  - wget -O cmake.sh https://cmake.org/files/v3.10/cmake-3.10.0-rc1-Linux-x86_64.sh 
  - sudo sh cmake.sh --skip-license --exclude-subdir --prefix=/usr/local
  - sudo apt-get install libmysqlclient15-dev libmysql++-dev
  - eval "${MATRIX_EVAL}"


script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j8