matrix:
  include:
    - os: linux
      sudo: required
      compiler: gcc

language: cpp

branches:
  only:
    - master

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install clang-3.9
  - sudo apt-get install libace-dev
  - sudo apt-get install lua5.2 liblua5.2 liblua5.2-dev
  - sudo apt-get install build-essential autoconf libtool make cmake git-core
  - sudo apt-get install openssl libssl-dev libmysqlclient15-dev libmysql++-dev libreadline6-dev zlib1g-dev libbz2-dev

script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j8