matrix:
  include:
    - os: linux
      env: BUILD_SYSTEM=cmake C_COMPILER=gcc-7 CXX_COMPILER=g++-7
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-7
          - g++-7
      sudo: required

language: cpp

branches:
  only:
    - master

before_install:
  - sudo add-apt-repository ppa:george-edison55/cmake-3.x -y
  - sudo apt-get update -qq
#  - sudo apt-get install build-essential autoconf libtool make cmake git-core patch wget
  - sudo apt-get install libmysqlclient15-dev libmysql++-dev
  - if [ -n "${C_COMPILER}" ]; then export CC="${C_COMPILER}"; fi
  - if [ -n "${CXX_COMPILER}" ]; then export CXX="${CXX_COMPILER}"; fi

script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j8