language: cpp
os: linux
dist: xenial

matrix:
  include:
    - addons:
        apt:
          sources:
            - sourceline: 'ppa:mhier/libboost-latest'
          packages:
            - boost1.67
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - addons:
        apt:
          sources:
            - sourceline: 'ppa:mhier/libboost-latest'
          packages:
            - boost1.67
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

branches:
  only:
    - master

before_install:
  - sudo apt-get install libmysqlclient-dev libmysql++-dev
  - eval "${MATRIX_EVAL}"

script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j8