
version: 0.01.{build}
image: Visual Studio 2017

# Branches to build
branches:
  only:
  - master

# Clone to the specified folder below, and only clone the latest commit without history.
clone_folder: c:\xijezu\

clone_depth: 1

# Enable parallel builds to speed up the compilation process.
build:
  parallel: true

# Initialize submodules.
before_build:
  - git submodule update --init --recursive

# Build core.
build_script:
  - cd c:\xijezu
  - cmake -DCMAKE_INSTALL_PREFIX="c:\xijezu\build\bin"
  - msbuild /m Project.sln