#ifndef PACKETS_TS_CS_STOP_BOOTH_H
#define PACKETS_TS_CS_STOP_BOOTH_H

#include "Packet/PacketDeclaration.h"

#define TS_CS_STOP_BOOTH_DEF(_)

CREATE_PACKET(TS_CS_STOP_BOOTH, 701);

#endif // PACKETS_TS_CS_STOP_BOOTH_H
