#ifndef PACKETS_TS_CS_REQUEST_LOGOUT_H
#define PACKETS_TS_CS_REQUEST_LOGOUT_H

#include "Packet/PacketDeclaration.h"

#define TS_CS_REQUEST_LOGOUT_DEF(_)

CREATE_PACKET(TS_CS_REQUEST_LOGOUT, 26);

#endif // PACKETS_TS_CS_REQUEST_LOGOUT_H
