#ifndef PACKETS_TS_CS_BATTLE_ARENA_EXERCISE_READY_H
#define PACKETS_TS_CS_BATTLE_ARENA_EXERCISE_READY_H

#include "Packet/PacketDeclaration.h"

#define TS_CS_BATTLE_ARENA_EXERCISE_READY_DEF(_) \
	_(simple)(bool, bReady)

// Since EPIC_8_1
CREATE_PACKET(TS_CS_BATTLE_ARENA_EXERCISE_READY, 4708);

#endif // PACKETS_TS_CS_BATTLE_ARENA_EXERCISE_READY_H
