#ifndef PACKETS_TS_CS_REQUEST_FARM_INFO_H
#define PACKETS_TS_CS_REQUEST_FARM_INFO_H

#include "Packet/PacketDeclaration.h"

#define TS_CS_REQUEST_FARM_INFO_DEF(_)

// Since EPIC_7_3
CREATE_PACKET(TS_CS_REQUEST_FARM_INFO, 6000);

#endif // PACKETS_TS_CS_REQUEST_FARM_INFO_H
