#ifndef PACKETS_TS_CS_HUNTAHOLIC_LEAVE_INSTANCE_H
#define PACKETS_TS_CS_HUNTAHOLIC_LEAVE_INSTANCE_H

#include "Packet/PacketDeclaration.h"

#define TS_CS_HUNTAHOLIC_LEAVE_INSTANCE_DEF(_)

CREATE_PACKET(TS_CS_HUNTAHOLIC_LEAVE_INSTANCE, 4005);

#endif // PACKETS_TS_CS_HUNTAHOLIC_LEAVE_INSTANCE_H
