#ifndef PACKETS_TS_CS_TURN_ON_PK_MODE_H
#define PACKETS_TS_CS_TURN_ON_PK_MODE_H

#include "Packet/PacketDeclaration.h"

#define TS_CS_TURN_ON_PK_MODE_DEF(_)

CREATE_PACKET(TS_CS_TURN_ON_PK_MODE, 800);

#endif // PACKETS_TS_CS_TURN_ON_PK_MODE_H
