#ifndef PACKETS_TS_CS_RETURN_LOBBY_H
#define PACKETS_TS_CS_RETURN_LOBBY_H

#include "Packet/PacketDeclaration.h"

#define TS_CS_RETURN_LOBBY_DEF(_)

CREATE_PACKET(TS_CS_RETURN_LOBBY, 23);

#endif // PACKETS_TS_CS_RETURN_LOBBY_H
