#ifndef PACKETS_TS_CS_OPEN_ITEM_SHOP_H
#define PACKETS_TS_CS_OPEN_ITEM_SHOP_H

#include "Packet/PacketDeclaration.h"

#define TS_CS_OPEN_ITEM_SHOP_DEF(_)

CREATE_PACKET(TS_CS_OPEN_ITEM_SHOP, 10000);

#endif // PACKETS_TS_CS_OPEN_ITEM_SHOP_H
