#ifndef PACKETS_TS_CS_CHECK_BOOTH_STARTABLE_H
#define PACKETS_TS_CS_CHECK_BOOTH_STARTABLE_H

#include "Packet/PacketDeclaration.h"

#define TS_CS_CHECK_BOOTH_STARTABLE_DEF(_)

CREATE_PACKET(TS_CS_CHECK_BOOTH_STARTABLE, 711);

#endif // PACKETS_TS_CS_CHECK_BOOTH_STARTABLE_H
