#ifndef PACKETS_TS_CS_REQUEST_FARM_MARKET_H
#define PACKETS_TS_CS_REQUEST_FARM_MARKET_H

#include "Packet/PacketDeclaration.h"

#define TS_CS_REQUEST_FARM_MARKET_DEF(_)

// Since EPIC_7_3
CREATE_PACKET(TS_CS_REQUEST_FARM_MARKET, 6008);

#endif // PACKETS_TS_CS_REQUEST_FARM_MARKET_H
