#ifndef PACKETS_TS_CS_INSTANCE_GAME_EXIT_H
#define PACKETS_TS_CS_INSTANCE_GAME_EXIT_H

#include "Packet/PacketDeclaration.h"

#define TS_CS_INSTANCE_GAME_EXIT_DEF(_)

// Since EPIC_6_3
CREATE_PACKET(TS_CS_INSTANCE_GAME_EXIT, 4251);

#endif // PACKETS_TS_CS_INSTANCE_GAME_EXIT_H
