#ifndef PACKETS_TS_CS_INSTANCE_GAME_SCORE_REQUEST_H
#define PACKETS_TS_CS_INSTANCE_GAME_SCORE_REQUEST_H

#include "Packet/PacketDeclaration.h"

#define TS_CS_INSTANCE_GAME_SCORE_REQUEST_DEF(_)

// Since EPIC_6_3
CREATE_PACKET(TS_CS_INSTANCE_GAME_SCORE_REQUEST, 4252);

#endif // PACKETS_TS_CS_INSTANCE_GAME_SCORE_REQUEST_H
