#ifndef PACKETS_TS_CS_CHANGE_SUMMON_NAME_H
#define PACKETS_TS_CS_CHANGE_SUMMON_NAME_H

#include "Packet/PacketDeclaration.h"

#define TS_CS_CHANGE_SUMMON_NAME_DEF(_) \
	_(string)(szName, 19)

CREATE_PACKET(TS_CS_CHANGE_SUMMON_NAME, 323);

#endif // PACKETS_TS_CS_CHANGE_SUMMON_NAME_H
