#ifndef PACKETS_TS_SC_BATTLE_ARENA_RECONNECT_BATTLE_H
#define PACKETS_TS_SC_BATTLE_ARENA_RECONNECT_BATTLE_H

#include "Packet/PacketDeclaration.h"

#define TS_SC_BATTLE_ARENA_RECONNECT_BATTLE_DEF(_) \
	_(string)(szName, 19) \
	_(simple)(uint32_t, newHandle)

// Since EPIC_8_1
CREATE_PACKET(TS_SC_BATTLE_ARENA_RECONNECT_BATTLE, 4715);

#endif // PACKETS_TS_SC_BATTLE_ARENA_RECONNECT_BATTLE_H
