#ifndef PACKETS_TS_SC_SHOW_CREATE_ALLIANCE_H
#define PACKETS_TS_SC_SHOW_CREATE_ALLIANCE_H

#include "Packet/PacketDeclaration.h"

#define TS_SC_SHOW_CREATE_ALLIANCE_DEF(_)

CREATE_PACKET(TS_SC_SHOW_CREATE_ALLIANCE, 660);

#endif // PACKETS_TS_SC_SHOW_CREATE_ALLIANCE_H
