#ifndef PACKETS_TS_SC_SHOW_SOULSTONE_CRAFT_WINDOW_H
#define PACKETS_TS_SC_SHOW_SOULSTONE_CRAFT_WINDOW_H

#include "Packet/PacketDeclaration.h"

#define TS_SC_SHOW_SOULSTONE_CRAFT_WINDOW_DEF(_)

CREATE_PACKET(TS_SC_SHOW_SOULSTONE_CRAFT_WINDOW, 259);

#endif // PACKETS_TS_SC_SHOW_SOULSTONE_CRAFT_WINDOW_H
