#ifndef PACKETS_TS_SC_SHOW_CREATE_GUILD_H
#define PACKETS_TS_SC_SHOW_CREATE_GUILD_H

#include "Packet/PacketDeclaration.h"

#define TS_SC_SHOW_CREATE_GUILD_DEF(_)

CREATE_PACKET(TS_SC_SHOW_CREATE_GUILD, 650);

#endif // PACKETS_TS_SC_SHOW_CREATE_GUILD_H
