#ifndef PACKETS_TS_SC_HUNTAHOLIC_BEGIN_COUNTDOWN_H
#define PACKETS_TS_SC_HUNTAHOLIC_BEGIN_COUNTDOWN_H

#include "Packet/PacketDeclaration.h"

#define TS_SC_HUNTAHOLIC_BEGIN_COUNTDOWN_DEF(_)

// Since EPIC_6_3
CREATE_PACKET(TS_SC_HUNTAHOLIC_BEGIN_COUNTDOWN, 4012);

#endif // PACKETS_TS_SC_HUNTAHOLIC_BEGIN_COUNTDOWN_H
