#ifndef PACKETS_TS_SC_HUNTAHOLIC_MAX_POINT_ACHIEVED_H
#define PACKETS_TS_SC_HUNTAHOLIC_MAX_POINT_ACHIEVED_H

#include "Packet/PacketDeclaration.h"

#define TS_SC_HUNTAHOLIC_MAX_POINT_ACHIEVED_DEF(_)

CREATE_PACKET(TS_SC_HUNTAHOLIC_MAX_POINT_ACHIEVED, 4010);

#endif // PACKETS_TS_SC_HUNTAHOLIC_MAX_POINT_ACHIEVED_H
