# This is a basic workflow to help you get started with Actions

name: build

on: [ push, pull_request, workflow_dispatch ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  linux:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential ninja-build cmake pkg-config tar curl zip unzip
          pip3 install conan==1.*

      # Runs a set of commands using the runners shell
      - name: Build
        run: |
          git submodule -q update --init --recursive
          mkdir build
          cd build
          cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release
          ninja
